const redButton=document.querySelector('.red');
redButton;
const greenButton=document.querySelector('.red');
greenButton;
const blueButton=document.querySelector('.red');
blueButton;
const buttons = document.querySelectorAll('button');
buttons;
buttons.length;
box;
buttons.forEach(button => {button.addEventListener('click',() => {const color = button.innerHTML; box.style.background = color; }); });
